#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
echo "Removing legacy Vendor Stand files..."
rm -f "src/client/java/domestia_vendor_choice/client/VendorStandBlockEntityRenderState.java"
rm -f "src/client/java/domestia_vendor_choice/client/VendorStandBlockEntityRenderer.java"
rm -f "src/client/java/domestia_vendor_choice/client/VendorStandScreen.java"
rm -f "src/main/java/domestia_vendor_choice/VendorStandBlock.java"
rm -f "src/main/java/domestia_vendor_choice/VendorStandBlockEntity.java"
rm -f "src/main/java/domestia_vendor_choice/VendorStandData.java"
rm -f "src/main/java/domestia_vendor_choice/VendorStandOpenPayload.java"
rm -f "src/main/java/domestia_vendor_choice/VendorStandSavePayload.java"
rm -f "src/main/resources/assets/domestia_vendor_choice/blockstates/vendor_stand.json"
rm -f "src/main/resources/assets/domestia_vendor_choice/items/vendor_stand.json"
rm -f "src/main/resources/assets/domestia_vendor_choice/models/block/vendor_note_stand.json"
rm -f "src/main/resources/assets/domestia_vendor_choice/models/item/vendor_stand.json"
rm -f "src/main/resources/data/domestia_vendor_choice/advancement/recipes/decorations/vendor_stand.json"
rm -f "src/main/resources/data/domestia_vendor_choice/loot_table/blocks/vendor_stand.json"
rm -f "src/main/resources/data/domestia_vendor_choice/recipe/vendor_stand.json"
echo "Done. Vendor Note normalization cleanup complete."
